{% set name = "airflow-common-operators" %}
{% set version = "0.1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-common-operators/airflow_common_operators-{{ version }}.tar.gz
  sha256: a02ed3184f16ae862eb6fb4ecc40b019c6ec84a5e292fedc65edb1275a7ebc79

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.8,<3
    - pydantic >=2

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_common_operators

about:
  home: https://github.com/airflow-laminar/airflow-common-operators
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Common Airflow Operators / Tasks
  description: Common Airflow Operators / Tasks
  dev_url: https://github.com/airflow-laminar/airflow-common-operators

extra:
  recipe-maintainers:
    - timkpaine
